workflows:
  android-workflow:
    name: MediCall Android
    max_build_duration: 60
    environment:
      flutter: 3.22.2
      java: 17
    scripts:
      - name: Fetch dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
