workflows:
  android-workflow:
    name: MediCall Android
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Recreate Android and Get dependencies
        script: |
          flutter create . --platforms=android
          flutter pub get
      - name: Fix Core Library Desugaring
        script: |
          cd android
          echo "android.defaults.buildfeatures.desugarabicg=true" >> gradle.properties
      - name: Build APK
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
